version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypass
    ports:
     - "5432:5432"
  dbweb:
    image: moritanosuke/docker-pgweb
    restart: always
    environment:
      POSTGRES: db
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: SpAuthDataBase
    ports:
     - "80:80"
    depends_on:
     - db 
  sp.auth:
    image: sp.auth.service:v01
    build: .
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
     - "5000:5000"
    depends_on:
     - db